<a href="https://colab.research.google.com/github/ummehub/ml-project-short-title./blob/main/ML_LAB01_157_HABIBA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  import numpy as np
  import pandas as pd

In [12]:
# LAB 1: Welcome to Machine Learning
# Student name: _______umme habiba_____________
# Student ID: _________157_____________

In [1]:
print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.


In [7]:
import numpy as np

np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])

print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])


Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]


In [15]:
import numpy as np

np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])

print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])

print('Minimum:', marks.min())
print('Standard deviation:', marks.std())

bonus_marks = marks + 5
print('Bonus marks:', bonus_marks)
print('Original marks:', marks)

print('Number passed:', np.sum(marks >= 50))

matrix = marks.reshape(2, 3)
print('2 × 3 matrix:')
print(matrix)


Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]
Minimum: 48
Standard deviation: 14.372040758206733
Bonus marks: [60 77 53 95 71 86]
Original marks: [55 72 48 90 66 81]
Number passed: 5
2 × 3 matrix:
[[55 72 48]
 [90 66 81]]


In [13]:
import numpy as np

marks = np.array([45, 67, 32, 80, 55, 39])

minimum = np.min(marks)
std_dev = np.std(marks)
print("Minimum mark:", minimum)
print("Standard deviation:", std_dev)

bonus_marks = marks + 5
print("Original marks:", marks)
print("Marks after bonus:", bonus_marks)

passed = np.sum(marks >= 40)
print("Number of students passed:", passed)

matrix = marks.reshape(2, 3)
print("2 × 3 Matrix:")
print(matrix)


Minimum mark: 32
Standard deviation: 16.482313753434823
Original marks: [45 67 32 80 55 39]
Marks after bonus: [50 72 37 85 60 44]
Number of students passed: 4
2 × 3 Matrix:
[[45 67 32]
 [80 55 39]]


In [11]:
import pandas as pd

data = {
    'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
    'study_hours': [2, 5, 1, 7, 3, 6],
    'sleep_hours': [8, 6, 9, 5, 7, 6],
    'attendance': [70, 88, 55, 95, 75, 91],
    'snacks': [3, 2, 5, 1, 4, 2],
    'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

display(df)

df.info()

print(df[['study_hours', 'sleep_hours', 'attendance', 'snacks']].describe())



,student,study_hours,sleep_hours,attendance,snacks,passed
0,Asha,2,8,70,3,Yes
1,Babu,5,6,88,2,Yes
2,Chayan,1,9,55,5,No
3,Dipa,7,5,95,1,Yes
4,Emon,3,7,75,4,No
5,Farah,6,6,91,2,Yes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   student      6 non-null      object
 1   study_hours  6 non-null      int64 
 2   sleep_hours  6 non-null      int64 
 3   attendance   6 non-null      int64 
 4   snacks       6 non-null      int64 
 5   passed       6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes
       study_hours  sleep_hours  attendance    snacks
count     6.000000     6.000000    6.000000  6.000000
mean      4.000000     6.833333   79.000000  2.833333
std       2.366432     1.471960   15.192103  1.471960
min       1.000000     5.000000   55.000000  1.000000
25%       2.250000     6.000000   71.250000  2.000000
50%       4.000000     6.500000   81.500000  2.500000
75%       5.750000     7.750000   90.250000  3.750000
max       7.000000     9.000000   95.000000  5.000000


In [14]:
features = ['study_hours', 'sleep_hours', 'attendance', 'snacks']
label = 'passed'

print("Features:", features)
print("Label:", label)

print("Samples:", df.shape[0])
print("Columns:", df.shape[1])

print(df[df['attendance'] >= 80])

print(df[df['passed'] == 'Yes']['study_hours'].mean())

print(df.sort_values('attendance', ascending=False))

print("No, this tiny dataset does not prove that snack purchases cause failure. It only shows an association in this small dataset. Other factors may affect the results, and correlation does not prove causation.")



Features: ['study_hours', 'sleep_hours', 'attendance', 'snacks']
Label: passed
Samples: 6
Columns: 6
  student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
5.0
  student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No
No, this tiny dataset does not prove that snack purchases cause failure. It only shows an association in this small dataset. Other factors may affect the results, and correlation does not prove causatio

In [9]:
import random
import numpy as np

def generate_scores(use_seed):
    if use_seed:
        random.seed(42)
        np.random.seed(42)
    return np.random.randint(40, 101, size=5)

print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))


Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]
